config/routes.rb
Rails.application.routes.draw do
  root "home#index"
 resources  :home , :users , :session , :stores , :addresses , :products ,
 						:product_variations ,:product_skus , :cart_items
 resources 	:orders, only: [:new, :create, :show] do
  resources :order_items, only: [:index, :show]
end			
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable , polymorphic:  true

  validates :address_line , :city , :state , :pincode , presence: true
end

app/models/buyer.rb
class Buyer < User
	has_many :addresses , as: :addressable
	has_one_attached :image
	has_many :orders , dependent: :destroy
	has_many :cart_items  ,dependent: :destroy
	has_one :cart
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :buyer , class_name: "User"
  has_many :cart_items ,dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :buyer
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
has_many :sub_categories , dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buyer
  has_many :order_items, dependent: :destroy
 end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  # belongs_to :sub_category
  has_many :cart_items
end

app/models/product_sku.rb
class ProductSku < ApplicationRecord
  belongs_to :product_variation
end

app/models/seller.rb
class Seller < User
  has_many :addresses, as: :addressable
  has_many :stores, dependent: :destroy
  has_many :products, through: :stores

  has_one_attached :image
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :seller, class_name: "User"

  validates :name , :description , presence: true

  has_many :products , dependent: :destroy
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord

  scope :type_seller, -> {where(type:'Seller')}

	has_secure_password
	has_many :stores ,  dependent: :destroy
	validates :type,:full_name,:email,:password,:phone, presence: true
	
 	before_validation :normalize_name, on: :create

  validates :password, confirmation: true

 	validate :password_complexity

 	validates :email,
      uniqueness: { message: "has already been taken" },
      format: { with: /\A[\w\.-]+@[\w\.-]+\.[a-zA-Z]{2,}\z/, message: "is not a valid email address" }

  validates :phone, format: { with: /\A(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[6789]\d{9}\z/,
                      message: "is not a valid Indian mobile number" }
  
  def password_complexity
    if password.present? && !password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{5,}$/)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, one digit, and be a minimum of 5 characters."
    end
  end

  private
    def normalize_name
      self.full_name = full_name.capitalize
    end


end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	skip_before_action :auhenticate_user, only: [:index]
	def index
		if @current_user&.type == "Buyer"
		 @stores = Store.all
		else
		@stores = current_user.stores
	  end
	end

	def show
		@store = current_user.stores.find(params[:id])
		 @products = @store.products
	end

	def new
		@store = Store.new
	end

	def create
		@store = current_user.stores.build(store_params)

		if @store.save
			redirect_to @store
		else 
			render :new
		end
	end

	def edit
		@store = current_user.stores.find(params[:id])
	end

	def update
		@store = current_user.stores.find(params[:id])
		if @store.update(store_params)
			redirect_to (@store)
		else
			render :edit
		end
	end

	def destroy
		@store = current_user.stores.find(params[:id])
		@store.destroy

		redirect_to stores_path
	end

	private
  def store_params
    params.require(:store).permit(:name,:description,:seller_id)
  end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/stores/_form.html.erb
 <%= render  "shared/seller_nav"%>
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center">Edit Store Form</h2>
			<%= form_with  model: @store  do |form|%>

				<div class="mb-3">
					<%= form.collection_select :seller_id, Seller.order(:full_name), :id,:full_name%>
				</div>

				<div class="mb-3">
					<%= form.label :name%>
					<%= form.text_field :name,class: "form-control"%>
				</div>

				<div class="mb-3">
					<%= form.label :description%>
					<%= form.text_field :description,class: "form-control"%>
				</div>

			  <div class="mb-3">
					<%= form.submit "Submit",class: "btn btn-success" %>
				</div>
			<% end %>
	</div>
</div>

app/views/stores/edit.html.erb
<%= render "form" , store: @store %>

app/views/stores/index.html.erb
<% if @current_user&.type == "Buyer" %>
<body>
    <%= render  "shared/buyer_header"%>
    <main>
      <section class="hero-section">
        <% @stores.each do |store|%>
          <div class="hero-slider">
            <div class="slide active">
              <div class="hero-content">
                <h1><%= link_to store.name, store %></h1>
                <p><%= store.description%></p>
                <button class="shop-now-button">Shop Now</button>
              </div>
              <img src="shoping.jpg" alt="Slide 1">
            </div>
            <% end %> 
      </section>
  	</main>

    <footer>
        <p>&copy; 2025 My E-commerce Website. All Rights Reserved.</p>
    </footer>
    <%= javascript_include_tag "home_index" %>

</body>
</html>
<% else %>

 <%= render  "shared/seller_nav"%>

 <h2>My Stores</h2>
<ul>
	<% @stores.each do |store|%>
		<li>
	    <%= link_to store.name, store %> 
	  </li>
	<% end %> 
</ul>
<%= link_to "Add new store" , new_store_path%>
<% end %>

app/views/stores/new.html.erb
<%= render  "shared/seller_nav"%>
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center">Store Form</h2>

    <%= form_with model: @store do |form| %>
      <div class="mb-3">
        <%= form.hidden_field :seller_id, value:@current_user.id  %>
      </div>

      <div class="mb-3">
        <%= form.label :Store_name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control" %>
      </div>

      <div class="text-center">
        <%= form.submit "Submit", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/stores/show.html.erb
<% if @current_user&.type == "Buyer" %>
<%= render  "shared/buyer_header"%>

<h1><%= @store.name %> Products</h1>
<% @products.each do |product| %>
  <div class="product-card">
    <h3><%= product.name %></h3>
    <p><%= product.description %></p>
    <p>₹<%= product.price %></p>
    <%= link_to "Add to Cart", "/cart_items?quantity=1&product_id=#{product.id}", data:{ turbo_method: :post }, class: 'btn btn-success' %>

    <%# <%= button_to "Add to Cart",  onclick: "alert('add-to-cart-button!'); return false;", method: :get %>

  </div>
<% end %>

<% else %> 
<%= render  "shared/seller_nav"%>

 <h3><%= @store.name %></h3>
   
<p><%= @store.description %></p>

<p><%= @store.seller_id %></p>
<ul>
<li><%= link_to "Edit" , edit_store_path(@store)%></li>
<li><%= link_to "Delete" , store_path(@store), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
                </ul>
<% end %>