config/routes.rb
Rails.application.routes.draw do
  root "home#index"
 resources  :home , :users , :session , :stores , :addresses , :products ,
 						:product_variations ,:product_skus , :cart_items
 resources 	:orders, only: [:new, :create, :show] do
  resources :order_items, only: [:index, :show]
end			
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable , polymorphic:  true

  validates :address_line , :city , :state , :pincode , presence: true
end

app/models/buyer.rb
class Buyer < User
	has_many :addresses , as: :addressable
	has_one_attached :image
	has_many :orders , dependent: :destroy
	has_many :cart_items  ,dependent: :destroy
	has_one :cart
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :buyer , class_name: "User"
  has_many :cart_items ,dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :buyer
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
has_many :sub_categories , dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buyer
  has_many :order_items, dependent: :destroy
 end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  # belongs_to :sub_category
  has_many :cart_items
end

app/models/product_sku.rb
class ProductSku < ApplicationRecord
  belongs_to :product_variation
end

app/models/seller.rb
class Seller < User
  has_many :addresses, as: :addressable
  has_many :stores, dependent: :destroy
  has_many :products, through: :stores

  has_one_attached :image
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :seller, class_name: "User"

  validates :name , :description , presence: true

  has_many :products , dependent: :destroy
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord

  scope :type_seller, -> {where(type:'Seller')}

	has_secure_password
	has_many :stores ,  dependent: :destroy
	validates :type,:full_name,:email,:password,:phone, presence: true
	
 	before_validation :normalize_name, on: :create

  validates :password, confirmation: true

 	validate :password_complexity

 	validates :email,
      uniqueness: { message: "has already been taken" },
      format: { with: /\A[\w\.-]+@[\w\.-]+\.[a-zA-Z]{2,}\z/, message: "is not a valid email address" }

  validates :phone, format: { with: /\A(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[6789]\d{9}\z/,
                      message: "is not a valid Indian mobile number" }
  
  def password_complexity
    if password.present? && !password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{5,}$/)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, one digit, and be a minimum of 5 characters."
    end
  end

  private
    def normalize_name
      self.full_name = full_name.capitalize
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# skip_before_action :require_login, only: [:new, :create]

	 skip_before_action :auhenticate_user, only: [:create, :new,:index]


	def index
		@users = User.all
	end

	def show
	  # @user = User.find(params[:id])
	   @user=User.find_by(id: session[:user_id])
	end

	def new
	  @user = User.new
	end	

	def create
    @user = User.create(user_params)

    if @user.valid?
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages.join(', ')
        redirect_to new_user_path
    end
  end	

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)

			redirect_to user_path
		else
			render :edit
		end
	end

	def destroy
		
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_path
	end

	private
  def user_params
    params.require(:user).permit(:type , :full_name , :email ,:password,:password_confirmation,  :phone , :image)
  end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_registration.html.erb
<header>
  <nav>
    <div class="logo">
        <a href="/home/index">ECommerce</a>
    </div>
    <ul>
      <li><a href="/home/index">Home</a></li>
      <li><a href="/products/">Products</a></li>
      <li><a href="/stores/">Stores</a></li>
      <li><%= link_to "Log out", session_path(@user), data:  { turbo_method: :delete,  turbo_confirm: "Are you sure?" } %></li>
    </ul>
  </nav>
</header> 
	<div class="container d-flex justify-content-center mt-5">
	  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
	    <h2 class="text-dark mb-4 text-center">Edit Registration form</h2>
				<%= form_with  model: @user , url: user_path  do |form|%>

					<div class="mb-3">
						<%= form.label :type%>
						<%= form.select :type, ["Buyer", "Seller"] ,class: "form-control" %> 
					</div> 

					<div class="mb-3">
						<%= form.label :full_name%>
						<%= form.text_field :full_name,class: "form-control"%>
					</div>

					<div class="mb-3">
					<%= form.label :email%>
					<%= form.email_field :email,class: "form-control"%>
					</div>

					<div class="mb-3">
						<%= form.label :password%>
						<%= form.password_field :password_digest,class: "form-control"%>
					</div>

					<div class="mb-3">
						<%= form.label :phone%>
						<%= form.number_field :phone ,class: "form-control" %>
					</div>

					<div class="mb-3 text-center">
	          <%= form.label :image%>
						<%= form.file_field :image %>
       		 </div>

				  <div class="mb-3">
					<%= form.submit "Submit",class: "btn btn-success" %>
					</div>
				<% end %>
		</div>
	</div>

app/views/users/edit.html.erb
<%= render "user_registration" , user: @user %>

app/views/users/index.html.erb
<% @users.each do |user|%>

	<li>
        <%= link_to user.full_name, user_path(user) %>
      </li>
	<% end %>
</ul>




	<%= link_to "New User Register", new_user_path%>

app/views/users/new.html.erb
<%= render  "shared/login_nav"%>
   

	<div class="container d-flex justify-content-center mt-5">

	  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
	    <h2 class="text-dark mb-4 text-center">Registration form</h2>
				<%= form_with model: @user, url: users_path do |form|%>

					<div class="mb-3">
						<%= form.label :type%>
						<%= form.select :type, ["Buyer", "Seller"] ,class: "form-control" %>
					</div>

					<div class="mb-3">
						<%= form.label :full_name%>
						<%= form.text_field :full_name,class: "form-control"%>
					</div>

					<div class="mb-3">
						<%= form.label :email%>
						<%= form.email_field :email,class: "form-control"%>
					</div>

					<div class="mb-3">
						<%= form.label :password%>
						<%= form.password_field :password,class: "form-control"%>
					</div>

					<div class="mb-3">
						<%= form.label :confirm_password%>
						<%= form.password_field :password_confirmation,class: "form-control"%>
					</div>


					<div class="mb-3">
						<%= form.label :phone%>
						<%= form.number_field :phone ,class: "form-control" %>
					</div>

					<div class="mb-3">
						<%= form.label :image %>
	      		<%= form.file_field :image %>
					</div>

				  <div class="mb-3">
					<%= form.submit "Submit",class: "btn btn-success" %>
					</div>
				<% end %>
		</div>
	</div>

app/views/users/show.html.erb
<header>
  <nav>
    <div class="logo">
        <a href="/home/index">ECommerce</a>
    </div>
    <ul>
        <li><a href="/home/index">Home</a></li>
        <li><a href="/products/">Products</a></li>
        <li><a href="/stores/">Stores</a></li>
        <li><%= link_to "Log out", session_path(@user), data:  { turbo_method: :delete,  turbo_confirm: "Are you sure?" } %></li>
    </ul>
  </nav>
    </header>
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center">Welcome <%= @user.full_name %> </h2>
      <%= form_with  do |form|%>
        <div class="mb-3 text-center">
          <% if @user.image.attached?%>
          <%= image_tag @user.image , class: "rounded-circle w-25"%>
          <% end %>
        </div>

        <div class="mb-3 text-center">
          <%= form.label "type:"%>
          <%= @user.type%>
        </div>

        <div class="mb-3 text-center">
        <%= form.label "email:"%>
        <%= @user.email %>
        </div>

        <div class="mb-3 text-center">
          <%= form.label "phone:"%>
          <%= @user.phone %>
        </div>

        <ul class="list-inline text-center">
          <li class="list-inline-item"><%= link_to "Edit" , edit_user_path(@user),class: "btn btn-secondary inline"%></li>
          <li class="list-inline-item"><%= link_to "Delete" , user_path(@user), data: { turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } ,class: "btn btn-secondary" %></li>
                </ul>
            
      <% end %>
  </div>
</div>