config/routes.rb
Rails.application.routes.draw do
  root "home#index"
 resources  :home , :users , :session , :stores , :addresses , :products ,
 						:product_variations ,:product_skus , :cart_items
 resources 	:orders, only: [:new, :create, :show] do
  resources :order_items, only: [:index, :show]
end			
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable , polymorphic:  true

  validates :address_line , :city , :state , :pincode , presence: true
end

app/models/buyer.rb
class Buyer < User
	has_many :addresses , as: :addressable
	has_one_attached :image
	has_many :orders , dependent: :destroy
	has_many :cart_items  ,dependent: :destroy
	has_one :cart
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :buyer , class_name: "User"
  has_many :cart_items ,dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :buyer
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
has_many :sub_categories , dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buyer
  has_many :order_items, dependent: :destroy
 end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  # belongs_to :sub_category
  has_many :cart_items
end

app/models/product_sku.rb
class ProductSku < ApplicationRecord
  belongs_to :product_variation
end

app/models/seller.rb
class Seller < User
  has_many :addresses, as: :addressable
  has_many :stores, dependent: :destroy
  has_many :products, through: :stores

  has_one_attached :image
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :seller, class_name: "User"

  validates :name , :description , presence: true

  has_many :products , dependent: :destroy
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord

  scope :type_seller, -> {where(type:'Seller')}

	has_secure_password
	has_many :stores ,  dependent: :destroy
	validates :type,:full_name,:email,:password,:phone, presence: true
	
 	before_validation :normalize_name, on: :create

  validates :password, confirmation: true

 	validate :password_complexity

 	validates :email,
      uniqueness: { message: "has already been taken" },
      format: { with: /\A[\w\.-]+@[\w\.-]+\.[a-zA-Z]{2,}\z/, message: "is not a valid email address" }

  validates :phone, format: { with: /\A(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[6789]\d{9}\z/,
                      message: "is not a valid Indian mobile number" }
  
  def password_complexity
    if password.present? && !password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{5,}$/)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, one digit, and be a minimum of 5 characters."
    end
  end

  private
    def normalize_name
      self.full_name = full_name.capitalize
    end


end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
	def  index
		@cart_items = current_user.cart_items

	end

	def show
		@cart_item = current_user.cart_items.find(params[:id])
		@product = @cart_item.product
	end

	def new
		@cart_item = CartItem.new
		
	end

	def create
  product_id = params[:product_id]
  quantity = params[:quantity] || 1

  @cart_item = current_user.cart_items.find_by(product_id: product_id)

  if @cart_item
    @cart_item.increment!(:quantity, quantity.to_i)
  else
    @cart_item = current_user.cart_items.build(cart_item_params)
    unless @cart_item.save
      render :new and return
    end
  end
  redirect_to cart_items_path
end

def destroy
		@cart_item = CartItem.find(params[:id])
		@cart_item.destroy

		redirect_to cart_items_path
	end

private
def cart_item_params
    params.permit(:quantity, :product_id)
end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/index.html.erb
 <%= render  "shared/buyer_header"%>

<table class="table">
  <thead>
    <tr>
      <th>Product</th>
      <th>Qty</th>
      <th>Price</th>
      <th>Subtotal</th>
      <th>View Details</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
   <% @cart_items.each do |cart_item|%>
      <tr>
        <td><%= cart_item.product.name %></td>
        <td><%= link_to cart_item.quantity, cart_item_path(cart_item) %></td>
        <td>₹<%= cart_item.product.price %></td>
        <td>₹<%= cart_item.quantity*cart_item.product.price %></td>
        <td><%= button_to "View Item", cart_item_path(cart_item), method: :get, class: "btn btn-primary" %></td>
        <td><%= link_to "Delete" ,"/cart_items/#{cart_item.id}", data: {
              turbo_method: :delete,turbo_confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
    <tr>
    	<td></td>
    	<td>Total Quantity : <%=@cart_items.sum { |item| item.quantity}%></td>
    	<td></td>
    	<td>Total Amount : <%=@cart_items.sum { |item| item.quantity * item.product.price }%></td>
    </tr>
  </tbody>

</table>
<%# 
<% @cart_items.each do |cart_item|%>
	<%# <ul>
    <li>Quantity : <%= link_to cart_item.quantity, cart_item_path(cart_item) %></li>
        
   <%#  <li>Product name : <%= cart_item.product.name %></li>
    <%# <li>Price :  ₹<%= cart_item.product.price %></li>
    <%# <li>Total :  ₹<%=cart_item.quantity*cart_item.product.price %></li>
	<%# <% end %
</ul> %>

app/views/cart_items/new.html.erb
<%= render  "shared/buyer_header"%>

<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center">Cart Items  form</h2>
	
			<%= form_with  model: @cart_item ,url: cart_items_path  do |form|%>
				
				<div class="mb-3">
					<%= form.label :quantity%>
					<%= form.text_field :quantity,class: "form-control"%>
				</div>
				<% @products.each do |product| %>
				<div class="mb-3">
					<%= form.hidden_field :product_id, value:product.id , class: "form-control"%>
				</div>
				<% end %>
				<div class="mb-3">
        <%= form.hidden_field :buyer_id, value:@current_user.id  %>
        </div>

			  <div class="mb-3">
				<%= form.submit "Submit",class: "btn btn-success" %>
				</div>
			<% end %>
	</div>
</div>

app/views/cart_items/show.html.erb
<%= render  "shared/buyer_header"%>

  <ul>
    <li>name : <%= @product.name %></li>
    <li>Quantity : <%= @cart_item.quantity%></li>
    <li>Price :  ₹<%= @product.price %></li>
    <li>Total :  ₹<%= @total_amount %></li>
		<li><%= link_to "Edit" , edit_cart_item_path(@cart_item)%></li>
		<li><%= link_to "Delete" , cart_item_path(@cart_item), data: {
		                turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
                </ul>
<%= button_to "Order now", new_order_path, method: :get, class: "btn btn-primary" %>




<!--<h3>Cart Items</h3>
<ul>
<li>Quantity: <%= @cart_item.quantity%></li>
 <li>Buyer id : <%= @cart_item.buyer_id %></li> 
 <li>Product id : <%= @cart_item.product_id %> </li>
 <li><%= link_to "Edit" , edit_cart_item_path(@cart_item)%></li>
<li><%= link_to "Delete" , cart_item_path(@cart_item), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>-->