config/routes.rb
Rails.application.routes.draw do
  root "home#index"
 resources  :home , :users , :session , :stores , :addresses , :products ,
 						:product_variations ,:product_skus , :cart_items
 resources 	:orders, only: [:new, :create, :show] do
  resources :order_items, only: [:index, :show]
end			
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable , polymorphic:  true

  validates :address_line , :city , :state , :pincode , presence: true
end

app/models/buyer.rb
class Buyer < User
	has_many :addresses , as: :addressable
	has_one_attached :image
	has_many :orders , dependent: :destroy
	has_many :cart_items  ,dependent: :destroy
	has_one :cart
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :buyer , class_name: "User"
  has_many :cart_items ,dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :buyer
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
has_many :sub_categories , dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buyer
  has_many :order_items, dependent: :destroy
 end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  # belongs_to :sub_category
  has_many :cart_items
end

app/models/product_sku.rb
class ProductSku < ApplicationRecord
  belongs_to :product_variation
end

app/models/seller.rb
class Seller < User
  has_many :addresses, as: :addressable
  has_many :stores, dependent: :destroy
  has_many :products, through: :stores

  has_one_attached :image
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :seller, class_name: "User"

  validates :name , :description , presence: true

  has_many :products , dependent: :destroy
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord

  scope :type_seller, -> {where(type:'Seller')}

	has_secure_password
	has_many :stores ,  dependent: :destroy
	validates :type,:full_name,:email,:password,:phone, presence: true
	
 	before_validation :normalize_name, on: :create

  validates :password, confirmation: true

 	validate :password_complexity

 	validates :email,
      uniqueness: { message: "has already been taken" },
      format: { with: /\A[\w\.-]+@[\w\.-]+\.[a-zA-Z]{2,}\z/, message: "is not a valid email address" }

  validates :phone, format: { with: /\A(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[6789]\d{9}\z/,
                      message: "is not a valid Indian mobile number" }
  
  def password_complexity
    if password.present? && !password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{5,}$/)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, one digit, and be a minimum of 5 characters."
    end
  end

  private
    def normalize_name
      self.full_name = full_name.capitalize
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	skip_before_action :auhenticate_user, only: [:index]
	def index
	  if @current_user&.type == "Buyer"
			@products = Product.all
		else
		 @products = current_user.products
		end
	end

	def show
		@product = current_user.products.find(params[:id])
	end
	
		def new 
			@product = Product.new
		end	
	
	def create

		@product = current_user.products.build(product_params)

		if @product.save
			redirect_to @product
		else 
			render :new
		end
	end	

	def edit
		@product = current_user.products.find(params[:id])
	end

	def update
		@product = current_user.products.find(params[:id])
		if @product.update(product_params)
			redirect_to (@product)
		else
			render :edit
		end
	end

	def destroy
		@product = current_user.products.find(params[:id])
		@product.destroy

		redirect_to products_path
	end

	private
  def product_params
    params.require(:product).permit(:name, :description, :price , :store_id)
  end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
  <%= render  "shared/seller_nav"%>
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center">Product form</h2>
			<%= form_with  model: @product  do |form|%>
				
				<div class="mb-3">
					<%= form.label :name%>
					<%= form.text_field :name,class: "form-control"%>
				</div>

				<div class="mb-3">
				<%= form.label :description%>
				<%= form.text_field :description,class: "form-control"%>
				</div>

				<div class="mb-3">
					<%= form.label :price%>
					<%= form.text_field :price,class: "form-control"%>
				</div>

				<div class="mb-3">
					<%= form.label :store_id%>
					<%= form.collection_select :store_id, Store.order(:name) , :id,:name%>
				</div>

			  <div class="mb-3">
				<%= form.submit "Submit",class: "btn btn-success" %>
				</div>
			<% end %>
	</div>
</div>

app/views/products/edit.html.erb
<%= render "form" , product: @product %>

app/views/products/index.html.erb
<% if @current_user&.type == "Buyer" %>
<body>
  <%= stylesheet_link_tag "home_index" %>
    <%= render  "shared/buyer_header"%>
    <main>

      <section class="featured-products-section">
        <h2>Featured Products</h2>
        <div class="slider-container">
          <button class="slider-btn prev-btn">Previous</button>
          <div class="product-slider">
            <% @products.each do |product| %>
              <div class="product-card">
                <%# Add your image tag here %>
                <h3><%= product.name %></h3>
                <p><%= product.description %></p>
                <span class="price"><%= product.price %></span>
                <%= link_to "Add to Cart", "/cart_items?quantity=1&product_id=#{product.id}", data: { turbo_method: :post }, class: 'btn btn-success' %>
              </div>
            <% end %>
          </div>
    <button class="slider-btn next-btn">Next</button>
  </div>
</section>
    </main>

    <footer>
        <p>&copy; 2025 My E-commerce Website. All Rights Reserved.</p>
    </footer>
    <%= javascript_include_tag "home_index" %>

</body>

<% else %>

 <%= render  "shared/seller_nav"%>
<h2>My Products</h2>
 <ul>

	<% @products.each do |product|%>
		<li>
	    <%= link_to product.name, product %> 
	  </li>
	<% end %> 
</ul>
<%= link_to "Add new product", new_product_path%> 

<% end %>

app/views/products/new.html.erb
 <%= render  "shared/seller_nav"%>

<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center">Product  form</h2>
	
			<%= form_with  model: @product  do |form|%>
				
				<div class="mb-3">
					<%= form.label :name%>
					<%= form.text_field :name,class: "form-control"%>
				</div>

				<div class="mb-3">
				<%= form.label :description%>
				<%= form.text_field :description,class: "form-control"%>
				</div>

				<div class="mb-3">
					<%= form.label :price%>
					<%= form.text_field :price,class: "form-control"%>
				</div>

				<div class="mb-3">
					<%= form.label :store_id%>
					<%= form.collection_select :store_id, @current_user.stores.order(:name) , :id,:name%>
				</div>

			  <div class="mb-3">
				<%= form.submit "Submit",class: "btn btn-success" %>
				</div>
			<% end %>
	</div>
</div>

app/views/products/show.html.erb
 <%= render  "shared/seller_nav"%>
<h2>Product Details</h2>
  <ul>
    <li><%= @product.name %></li>
    <li><%= @product.description %></li>
    <li><%= @product.price %></li>
    <li><%= @product.store_id %></li>
    <li><%= link_to "Edit" , edit_product_path(@product)%></li>
    <li><%= link_to "Delete" , product_path(@product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  </ul>